### ISSUE TITLE
Unable to use plugin in Grails 3.1.4 project

### ISSUE THREAD

**Issue by bhagwat** [vahidhedayati/RemoteSSH#4]
I used this in build.gradle:
`compile "org.grails.plugins:remotessh:3.0.1"`
Whenever I try to run the grails-app using `grails run-app` or `./gradlew bootRun` I get this error:
`| Error Error initializing classpath: inconsistent module metadata found. Descriptor: org.grails.plugins:RemoteSSH:3.0.1 Errors: bad module name: expected='remotessh' found='RemoteSSH' (Use --stacktrace to see the full trace)
`
I `tried` task and manually deleted the build folder with no luck.

**Comment by bhagwat** [comment]
Managed to work now. The documentation need to be updated for Grails 3.x. It should be 

`compile "org.grails.plugins:RemoteSSH:3.0.1"`

I found it here: https://bintray.com/vahid/maven/RemoteSSH/view

**Comment by vahidhedayati** [comment]
thanks will do
