### ISSUE TITLE
problem with encoding

### ISSUE THREAD

**Issue by higi** [vahidhedayati/RemoteSSH#6]
Hello, 

¨my problem is when i SCP file to any server, they have "weird"characters in file name.
like APP pro P+?ipom+?nky.pdf 
shoudl looks like APP pro Připomínky.pdf

any help please?

**Comment by vahidhedayati** [comment]
Hi Higi

Can you describe how you are doing it ? The plugin was written years ago and looking back on the docs I see I provided a tag lib method to make it easier - is it this method ?

The actual raw code to scp a file would be  

```
class TestController {

      def sshConfig

      def index() {
          RemoteSSH rsh = new RemoteSSH()
          rsh.setHost('localhost')
          rsh.setPort(22)
          rsh.setUsercommand('whoami')
          def g = rsh.Result(sshConfig)

          render "---- ${g}"

      }
```

https://github.com/vahidhedayati/RemoteSSH/tree/24885e6c4b3d5d5d3026e04aa566562333775cb5

RemoteSCP Call types:
 RemoteSCP rscp=new RemoteSCP(host, file, remotedir) 
 RemoteSCP rscp=new RemoteSCP(host, user, file, remotedir) 
 RemoteSCP rscp=new RemoteSCP(host, user, userpass, file, remotedir) 
 RemoteSCP rscp=new RemoteSCP(host, file, remotedir, port) 
 RemoteSCP rscp=new RemoteSCP(host, user, file, remotedir, port) 
 RemoteSCP rscp=new RemoteSCP(host, user, userpass, file, remotedir, port) 


```
def scp() {  
 RemoteSCP scp1=new RemoteSCP('localhost', 'myusername', 'mypassword', '/tmp/11.txt' ,'/var/tmp', port)
 def result=scp1.Result(sshConfig)

 def returnit="SCP file example:"+result
 render(view: "index", model: [ak: returnit])
 
}
```

Anyhow the actual bit of code that does the copying 
https://github.com/vahidhedayati/RemoteSSH/blob/b1d3b0ca7f40e9f6222476c46cdac20e1393db40/src/main/groovy/grails/plugin/remotessh/RemoteSCP.groovy#L53-L55

```
  SCPClient scp = conn.createSCPClient()
  scp.put(file, remotedir)
  conn.close()
```


It doesn't actually define the end file name just the dir it gets dropped into.

I have looked up https://mvnrepository.com/artifact/ch.ethz.ganymed/ganymed-ssh2 this is still the latest libs for the underlying technology

Perhaps use the jssh plugin ?  there is also https://grails.org/plugin/jsch-ssh2?skipRedirect=true  plugin too.

**Comment by higi** [comment]
Hello, u are the best:)
We are on grails 2.4.2, if u be so kind to add some aditional fields for encoding. Would be really appreciate.

**Comment by vahidhedayati** [comment]
will take a look later this evening in a few hours after work -

**Comment by vahidhedayati** [comment]
Hi Higi 

I haven't actually pushed the changes since I can't the code to work as it is - I have rolled back the plugin locally to what is on repo 
`scp: error: unexpected filename: ` 

https://github.com/sshnet/SSH.NET/pull/515

There is some info on this - 

Its a bit difficult for me to release it as it since - I can;t actually test it but can you do me a favour:
```
mkdir test 
cd test

git clone https://github.com/vahidhedayati/RemoteSSH -b grails2
git clone https://github.com/vahidhedayati/test-rssh
cd test-rssh
echo "edit the file then run app"
grails run-app
```

https://github.com/vahidhedayati/test-rssh/blob/master/grails-app/controllers/test/rssh/TestController.groovy#L26-L37

configure all of above and provide or test encoding locally ? can u see how that goes if that works I will roll out the rest of it correctly.

At the moment proper working version should be in ScpClient the rest of them need some tweaks once this works / confirmed working

**Comment by higi** [comment]
Hello, THX for changes.

There are two problems:
1.
Config.groovy settings is all right (like before test)
`remotessh.USER = "XXX"
remotessh.PASS="YYYYY"
remotessh.KEY=""
remotessh.KEYPASS=""
remotessh.PORT="22"`

error in log file:
`Cannot invoke method getConfig() on null object
java.lang.NullPointerException: Cannot invoke method getConfig() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at grails.plugin.remotessh.RemoteSSH.Result(RemoteSSH.groovy:19)
        at grails.plugin.remotessh.RemoteSSH$Result$1.call(Unknown Source)`

2.
when i do:
rscp.setFile("C:/_WORK_/test2.zip")
java.io.IOException: Remote scp terminated with error (scp: error: unexpected filename: C:/_WORK_/test2.zip).
My setting what i want to copy.

**Comment by vahidhedayati** [comment]
Basically I took out the java version of the plugin due to major changes in the revision update of ganyemed ssh libraries - as you can see here
https://github.com/vahidhedayati/RemoteSSH/commit/6402c3d8a71d3d0468a926637014a93479e0c2d0#diff-0282bbd42de919ea395de2c3c22b51b6R241

Anyhow If you have that demo project setup and working I suggest you refer to the latest updates sent 

Remember this is a test for now...

https://github.com/vahidhedayati/test-rssh/blob/master/grails-app/controllers/test/rssh/TestController.groovy#L25-L40

Do something like this as part of your test see if this works by providing the actual username and password if this works and does your file encoding correctly I will fix the rest and put the java files back which will need updates to its calls implementation

**Comment by higi** [comment]
i tested new version from u, and results are:
There are two problems:
1.
Config.groovy settings is all right (like before test)
remotessh.USER = "XXX" remotessh.PASS="YYYYY" remotessh.KEY="" remotessh.KEYPASS="" remotessh.PORT="22"

error in log file:
Cannot invoke method getConfig() on null object java.lang.NullPointerException: Cannot invoke method getConfig() on null object at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at grails.plugin.remotessh.RemoteSSH.Result(RemoteSSH.groovy:19) at grails.plugin.remotessh.RemoteSSH$Result$1.call(Unknown Source)

when i do:
rscp.setFile("C:/WORK/test2.zip")
java.io.IOException: Remote scp terminated with error (scp: error: unexpected filename: C:/WORK/test2.zip).
My settings what i want to copy.

**Comment by vahidhedayati** [comment]
I think you have missed the point literally you should have the two clones and updated
below and provided a localhost username password and a file and a local folder enabled utf-8 below and ran it to see very quickly does it scp locally the file as expected if so then i would have fixed rest and pushed it out - don't worry i have some old pc and will give it a go in a while again myself
```


def testScp() {
		RemoteSCP rscp=new RemoteSCP()

		rscp.host = "localhost"
		rscp.user = "username"
		rscp.port=22
		rscp.userpass="password"
		//rscp.file = "/tmp/Kispálés.txt"
		rscp.file = "/tmp/bahh.txt"
		rscp.remotedir = "/tmp/vh"
		//rscp.charsetName='UTF-8'
		def result=rscp.Result(sshConfig)
		println "ch ${rscp.charsetName}"
		render result

	}

```

**Comment by vahidhedayati** [comment]
the issue at the moment is very strange, I am getting the same problem on some old laptop..

basically i have pushed back and fixed the java files to support the latest libs of ganymed but for some reason it doesn't like the file being passed to it.

This is my first plugin and the confusion maybe around RemoteSCP imported from `ssh.RemoteSCP` vs 

https://github.com/vahidhedayati/test-rssh/blob/master/grails-app/controllers/test/rssh/TestController.groovy#L3

`import grails.plugin.remotessh.RemoteSCP`

Both called identical names one is the java version the other Groovy version of it - 

anyhow locally for me at the moment the plugin isn't working - will try looking around when I get time to see why this file input isn't liked 

`Remote scp terminated with error (scp: error: unexpected filename: /tmp/bahh.txt).`

**Comment by vahidhedayati** [comment]
Just to let you know I have got it working locally and will update the plugin on the grails 2 version of this plugin -  it simply is really round major changes and am using SFTPv3Client which is part of this build since hudson took on the plugin - rather confusing - you should be able to use the put method but it looks like its been made into streams and rather complex to work out what on earth is going on

**Comment by vahidhedayati** [comment]
Please refer to the most[ latest changes of this plugin - 0.9 ](https://github.com/vahidhedayati/RemoteSSH/tree/grails2#updates-on-09-of-grails-2-branch)

The actual test done locally all of which worked can be found on[ this sample site](
https://github.com/vahidhedayati/test-rssh/commit/fc25f9c826c5476d978905e7f1d3664b057c7b00)
```

Connection connection = sshUtilService.openConnection("localhost",22)
String ranCommand = sshUtilService.execute(connection,'mkdir /tmp/backup-test')
String ranCommand1 = sshUtilService.execute(connection,'echo "hi there" > /tmp/test.txt')
String readRemoteFile = sshUtilService.readRemoteFile('/tmp/test.txt',connection)
sshUtilService.writeFile('/tmp/test.txt','/tmp/backup-test/',connection)
		sshUtilService.writeFileWithName('/tmp/test.txt','/tmp/backup-test/Kispálés.text',connection)

```

All the new things you can do. For me all the tests in controller worked - I will close off ticket, if you are still having issues -please reopen it.

Am only rolling this out on grails 2. If anyone raises concerns or wants this to be rolled out on grails 3 version of plugin give me a shout
